### ISSUE TITLE
Exercise 6 extra 4 after profiler doesn't have throttle

### ISSUE THREAD

**Issue by diego0020** [kentcdodds/react-performance#104]
The comparison is not accurate because one side has cpu throttle and the other doesn't. 

![image](https://user-images.githubusercontent.com/7297450/145508250-68975a89-e5cc-4ee8-b341-48fbc166e450.png)

**Comment by kentcdodds** [comment]
Yup. That was a mistake when I recorded the video. If I ever do update the videos then I'll make sure to avoid that mistake.
