### ISSUE TITLE
Should Tracing API exercise be removed? API removed in React 17

### ISSUE THREAD

**Issue by vmerino** [kentcdodds/react-performance#107]
Hello!

I had a question in the Discord channel on whether the experimental trace API exercise should be removed (exercise 7 extra credit 1).  Per this link found in the react docs: https://fb.me/react-interaction-tracing, the tracing API was removed in React 17.  

Interestingly though, I see `"react": "^17.0.2",` in the dependencies and can still see interactions in the exercise: 

![image](https://user-images.githubusercontent.com/5444971/152846784-9913da37-53d5-4245-9f44-da91b58a222b.png)

Maybe it was just removed from the dev tools? Not sure.
Let me know if you need anything else.

Thanks!

**Comment by kentcdodds** [comment]
Yeah, that's odd. If anyone can figure out what the current state (or future plans) of this API are, then we can add a note in the exercise notes.
