### ISSUE TITLE
05.extra-1.js all the cells render when you click one of them

### ISSUE THREAD

**Issue by yzaroui** [kentcdodds/react-performance#108]
Even with splitting the contexts, all the cells still render. This is also visible on the production build on Netlify
https://react-performance.netlify.app/isolated/final/05.extra-1.js

And this is logicial because when you click on a cell the state (context) changes for all the cells.

Is there any other solution to avoid rendering all the cells?

**Comment by kentcdodds** [comment]
I'm afraid I don't have time to answer this in the issues, but you're welcome to bring questions like this to my office hours: https://kcd.im/office-hours.

**Comment by yzaroui** [comment]
I shouldn't have asked the question here because it is not the main subject in this issue, so forget about it 😄 

Your solution to this exercise is not accurate and does not work as expected (all the cells render). You my also need to re-record the video for this.

**Comment by kentcdodds** [comment]
I'm pretty confident I've looked at this before and you're misunderstanding something. I don't have time to look into it right now but I can during office hours if you wanna ask there.

**Comment by fedebabrauskas** [comment]
For anyone that noticed this issue, it will be reviewed in exercise 6.2.

Exercise 5.1 only focuses on the re-rendering of the `Grid` component, so the `Cell` components will continue re-rendering as they still consume the state from context.
