### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by mantey-github** [kentcdodds/react-performance#110]
This error appears in the console when ever i make changes to an exercise file. After the changes, when i go back to the exercise I am not able to scroll. Looks like there's an overlay (iframe) blocking the view. I have to refresh to get everything working

<img width="755" alt="Screenshot 2022-04-22 at 7 23 05 AM" src="https://user-images.githubusercontent.com/39991756/164883668-c9af420a-8dcd-411b-a29e-ca51c7a51f63.png">

**Comment by kentcdodds** [comment]
I believe this has been resolved.
