### ISSUE TITLE
1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

### ISSUE THREAD

**Issue by yevhen309** [kentcdodds/react-performance#112]
Basically the subj. 

The easiest way to reproduce: 
`docker-compose up`

In fact, any installation method will result in the error. 

Fixing the versions in the package.json doesn't help.

**Comment by kentcdodds** [comment]
Can you give me the whole output when you try?

**Comment by yevhen309** [comment]
Hi Kent, 

Basically this is the whole output:

![CleanShot 2022-05-22 at 09 00 18](https://user-images.githubusercontent.com/49063281/169683038-6f1c412b-0e9f-49ad-91a7-2b06a7fd5f57.png)

Sorry, when I created the issue, I couldn't find a webpack config to follow the instructions. My second attempt with 'stats.children: true':

![CleanShot 2022-05-22 at 09 04 04](https://user-images.githubusercontent.com/49063281/169683190-11ad0aa2-4d27-4b64-a9dc-427c15c9cb9c.png)

**Comment by kentcdodds** [comment]
Ah! Looks like workerize-loader doesn't yet support Webpack 5: https://github.com/developit/workerize-loader/issues/77

If we don't get a solution to that quickly then I'll figure something else out. Thanks for bringing this to my attention!

**Comment by kentcdodds** [comment]
Fixed! Thanks for your patience :)
