### ISSUE TITLE
Issue with Exercise 2 Extra Credit 2, Exercise 3 in regards to web workers.

### ISSUE THREAD

**Issue by jeremiahfallin** [kentcdodds/react-performance#113]
In exercise 2, extra credit 2 when adding the web worker I get this error:
![unknown](https://user-images.githubusercontent.com/18542660/169713962-5e9e6b95-4bd8-42ed-8a7b-23e4595d913e.png)

Which comes up both when I add the web worker myself and also when I check the final solution for the extra credit.

The error is also present in Exercise 3 and it prevents anything from rendering.

When building the workshop I got the following error which may be related:
```1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 1 error```

May be related to this issue:
https://github.com/kentcdodds/react-performance/issues/112

**Comment by kentcdodds** [comment]
Hi @jeremiahfallin!

This is a duplicate: #112

We're working on it. Shouldn't bee too long before we get a fix. Thanks!
