### ISSUE TITLE
Uncaught TypeError: (0 , _workerized_filter_cities__WEBPACK_IMPORTED_MODULE_2__.getItems) is not a function

### ISSUE THREAD

**Issue by fitzage** [kentcdodds/react-performance#115]
This is part of what shows up in #113 and then probably #112, except I'm not getting the (apparently now fixed) undefined error, just the `not a function` errors related to the workerization.

I still get the rest of the error from #112, and it happens in my exercises for lessons 3 and 4 as well as the final versions. Here is a screenshot from the final for exercise 3, showing nothing rendering, and the console errors.

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/1958/170915904-13652c11-1691-469a-ae78-42e35693993e.png">

**Comment by fitzage** [comment]
OK, this is very weird. I went back to the non-workerized filter-cities import, and was getting an error about how run from useAsync was not receiving a promise. I hadn’t had an issue with the non-workerized one before.

In an attempt to troubleshoot, I decided to add some console logging to the `filter-cities.js` file. I logged `allItems` and immediately the site started working. I removed the console log line and it stayed working. I don’t understand what was going on here. Now that this has started behaving, the workerized version works correctly also.

**Comment by androso** [comment]
![image](https://user-images.githubusercontent.com/59257555/172185169-698d644c-6a5f-490a-8d68-56e48624789e.png)
I'm experiencing the same error, and the only solution i've found is to re install the project. It happened on local so i tried gitpod but it sill happens after some time, not sure why 😅

**Comment by ognyan-kostadinov** [comment]
Not a fluke, happened for me too. Just like @fitzage I played around with using the non-workerized **_getCities_**, console logging here and there to investigate etc and it magically started working. If it's not going to be fixed definitively, could you leave the issue open or write a remark on some more visible spot (like project's README or the exercise's MD file) to make the users aware of this? Thanks in advance, the training is awesome so far!

**Comment by lenniezelk** [comment]
@kentcdodds kindly reopen this, the issue is still happening

**Comment by sunnatganiev** [comment]
The same error. The same attempt (console.log(allItems) in filter-cities.js). Worked!

**Comment by diomededavid** [comment]
The same error. Just pulled down repo today. 

![Screen Shot 2022-07-24 at 6 32 01 PM](https://user-images.githubusercontent.com/14153189/180681401-3c738d26-bbdd-4470-ab4f-f122ddf52a8b.png)

**Comment by medoror** [comment]
Same. Did the `workerize` api change?

**Comment by kentcdodds** [comment]
My guess is there's a bug in `workerize`. Anyone can feel free to make a minimal reproduction and report it in the https://github.com/developit/workerize-loader issue tracker. Unfortunately I still can't reproduce this issue myself:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/1500684/181074518-91690e4b-7a40-4ccd-9c63-ab267bdc5483.png">

**Comment by diomededavid** [comment]
@kent By adding `export default class makeFilterCitiesWorker {}` to the end of `filter-cities.js` seems to fix the issue.

**Comment by diomededavid** [comment]
By adding `export default class makeFilterCitiesWorker {}` to the end of `filter-cities.js` is a potential solution.

**Comment by anthony-kyle** [comment]
Can confirm that this makes the error go away for me. I just cloned the repo today.

> By adding `export default class makeFilterCitiesWorker {}` to the end of `filter-cities.js` is a potential solution.

**Comment by kentcdodds** [comment]
Thanks! I'll just stick that in then 👍

**Comment by kentcdodds** [comment]
Pretty sure this is a problem with workerize-loader. I'd anyone wants to dig further and file an issue on that project that would be the most helpful I think. At this point there isn't anything more we can do in this project.
