### ISSUE TITLE
React Performance, Exercise 2 final extra 2  with web workers doesn't work, also Ex 3 doesn't work

### ISSUE THREAD

**Issue by jzaburunov** [kentcdodds/react-performance#116]
Hi Kent. Just opened up a final version for exercise 2 extra credits 2 (or initial exercise 3) in a new tab and got the blank screen with error, something's wrong.

<img width="1728" alt="Screenshot 2022-09-07 at 10 45 45" src="https://user-images.githubusercontent.com/11402322/188821178-9fe220fa-1c5c-48e4-aea3-b49963dfd0cf.png">

**Comment by oscarwroche** [comment]
Same issue here for 2, 3 and 4

**Comment by reubenberghan** [comment]
I had the same issue and started playing around with downgrading the version of `workerize-loader`. Downgrading did work but I also tried deleting my `node_modules` and reinstalling (leaving `workerize-loader` at version `2.0.2`) which also worked for me.

Hopefully one of those options will work for you (ideally just deleting the `node_modules` and reinstalling).
