### ISSUE TITLE
1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

### ISSUE THREAD

**Issue by Prajwal-kh** [kentcdodds/react-performance#117]
_Hi guys could you please help me!! I am getting the same issue...I have updated webpack version along with the other dependencies updated versions. Please find the attachments of package.json and webpack.config.js._
![package](https://user-images.githubusercontent.com/60292269/192159804-e51351c6-d9cc-447c-a5f2-b6f2c2833db1.png)
![webpack](https://user-images.githubusercontent.com/60292269/192159736-f76b4e06-0101-495e-965e-793e3f3c072e.png)
8b75-92f3790178a1.png)

**Comment by kentcdodds** [comment]
I'm sorry, but this issue tracker is not webpack technical support.
