### ISSUE TITLE
Exercise 3 extra credit 1, avoid re-renders in selectedItem

### ISSUE THREAD

**Issue by pnadalini** [kentcdodds/react-performance#126]
In exercise 3 extra credit 1, you mention that you can do the same with `selectedItem`, I tied that out, and only had problems because I forgot to modify line 68 `if (prevProps.selectedItem !== nextProps.selectedItem) return false`
We need to change it to:
```
if (prevProps.selectedItem !== nextProps.selectedItem) {
    const id = prevProps.item.id
    const wasPrevSelected = prevProps.selectedItem?.id === id
    const isNowSelected = nextProps.selectedItem?.id === id
    return wasPrevSelected === isNowSelected
}
```

You can see it working with the Henderson selected example
![image](https://github.com/kentcdodds/react-performance/assets/26207809/dbe9faa0-a863-4bb4-9ec6-915d52e2e7da)

On a second note, your CONTRIBUTING.md is outdated, the egghead link is now `https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github`

**Comment by kentcdodds** [comment]
Thanks for letting me know! This issue will be helpful for anyone searching in the future :) Cheers!
