### ISSUE TITLE
Fix 04.js 

### ISSUE THREAD

**Issue by AhmedAymanM** [kentcdodds/react-performance#36]
Hello, I create PR #35 that fixes a bug that caused the items list to scroll to the top when hovering out of it.  
on debugging, I found that `onHighlightedIndexChange` returns `highlightedIndex` with value of `-1` when the mouse moves out of the list, this makes `rowVirtualizer.scrollToIndex` methof to scroll to the top 

![scroll bug](https://user-images.githubusercontent.com/535126/95404697-00a9f180-0916-11eb-8a3f-89b51d1da57b.gif)

have a good day! 😄 🎈

**Comment by kentcdodds** [comment]
Thank you!

**Comment by AhmedAymanM** [comment]
There is no need!
