### ISSUE TITLE
Can't access examples/code-splitting/main.js

### ISSUE THREAD

**Issue by 0xnoob** [kentcdodds/react-performance#77]
Hi,

at the end of the first exercise, it says:

>### Notes
>Another thing which we won’t cover in this workshop, but you should look into later, is using the webpackChunkName magic comment which will allow webpack to place common modules in the same chunk. This is good for components which you want loaded together in the same chunk (to reduce multiple requests for multiple modules which will likely be needed together).
>You can play around with this in the src/examples/code-splitting directory.

the files contains a link:
>// http://localhost:3000/isolated/examples/code-splitting/main.js

but visiting this link doesn't work, neither in development nor production build:
>Sorry... nothing here. To open one of the exercises, go to `/exerciseNumber`, for example: /1

I played around a little bit: I can only visit sites that are directly under `examples`, that's why the other example `unnecessary-rerenders.js` are accessible.
My solution was to simply move the `main.js` one folder up and update the module imports, because importing from deeper directories still works. 
I didn't create a pull request because I assume there is a problem somewhere else, which prevents accessing the deeper directory directly?

**Comment by kentcdodds** [comment]
Thanks for letting me know! Fixed this.
