### ISSUE TITLE
Exercise 3 - example unnecessary-rerenders.js - memoizing CountButton doesn't stop it from unnecessary re-renders.

### ISSUE THREAD

**Issue by 0xnoob** [kentcdodds/react-performance#78]
Hello,
[using React.memo on CountButton](https://github.com/kentcdodds/react-performance/blame/main/src/exercise/03.md#L109) doesn't stop it from rerendering, because it will always receive a new instance of the [`increment`](https://github.com/kentcdodds/react-performance/blame/main/src/exercise/03.md#L68) function.

There are a couple of ways to fix this:

- simply don't memoize `CountButton`, as the focus of the example is on `NameInput` anyway.
-  use `React.useCallback` on `increment` before passing it as a property (don't think that's a good solution, though).
- instead of `increment`, pass `setCount` as a property to `CountButton` and define `increment` inside that component.
- at the end of the example, it says _"that people can make the mistake of wrapping
_everything_ in `React.memo` which can actually slow down your app in some cases
and in all cases it makes your code more complex."_ maybe point them to look at the memoized `CountButton` in the React DevTools as an example of this? Because that's what I thought it boiled down to.

I hope this isn't too much nitpicking from me! :3

**Comment by kentcdodds** [comment]
Thanks for the feedback! I like your first and last suggestion 👍 I think we should not memoize it and then point out that the reason we didn't bother is because it wouldn't work without also memoizing `increment`.

Thanks for your help! Would you be interested in making a PR to update this?
