### ISSUE TITLE
GraphQL responds with 404

### ISSUE THREAD

**Issue by JekRock** [kentcdodds/react-performance#82]
Videos at https://epicreact.dev/modules/react-performance/react-performance-welcome stuck on loading. There is an error message in the console:
```
POST https://app.egghead.io/graphql 404

GraphQL Error (Code: 404): {"response":{"error":"","status":404},"request":{"query":"\n  query LessonData($slug: String!) {\n    video_resource(slug: $slug) {\n      slug\n      subtitles_url\n      lesson_view_url\n      dash_url\n      hls_url\n    }\n  }\n","variables":{"slug":"egghead-er-05-00-01-react-performance-welcome"}}}
```

**Comment by dealingwith** [comment]
@JekRock We're working hard on getting this bug resolved. In the meantime logging in with a different browser might solve the problem. Thanks for your patience.

This issue is related to the Epic React backend platform, not this repository specifically.

**Comment by JekRock** [comment]
Got it. Thanks for your response!
